PATCH  http://localhost:9000/employees/1 HTTP/1.1
content-type: application/json

{
    "firstName": "Phan Hoang",
    "lastName": "Vinh",
    "phoneNumber": "0923451789",
    "address": "38 Yen Bai",
    "email": "anv@gamil.com",
    "birthdat": "2000-02-14",
}