GET http://localhost:9000/products?product=máy giặt công nghiệp Speed Queen SCG060&category=643aea6cfe0175a768b74600&sup=642c48a62735b6c80ebfc02e&stockEnd=110 HTTP/1.1
content-type: application/json

